### ISSUE TITLE
Missing dependencies under Linux

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#197]
Field report; requires verification:

https://plus.google.com/b/105395755735629417704/photos/+DaveLeCompte/albums/6091614580982285041?cfem=1

**Comment by techninja** [comment]
@tsmaster Fancy I find myself here! I just recently wiped and redid my laptop with Ubuntu 14.10 x64 (latest stable with all the toppings), and what do you know, NW does not work at all because of this specific issue! A quick googling brought me to [this stackoverflow post about Chromium](http://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error).

But, there is no libdev.0 package. Looking in the comments, I find the incantation that _**does**_ work
```
sudo apt-get install libudev1:i386 -y
sudo ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
```
Though somewhat "hacky", this totally works and helps fill the hole, at least until NW fixes this issue (likely in NW 12).

**Comment by techninja** [comment]
Another subtle issue: Ubuntu users by default are not part of the `dialout` group, and need to be otherwise you can't access serial ports without `sudo`. Here's the fix to add the current user to dialout:
```
sudo usermod -a -G dialout $USER
```

Then logout/back in, or reboot the machine, and everything is happy once again.

Also, as far as cleanliness, we should either append a Linux `install.sh` shell script to the linuxpackage that does all this and close the ticket, and/or make sure we hear back from @tsmaster that these steps actually help him :)

**Comment by tsmaster** [comment]
now it's complaining about libnss3.so:

$ ./robopaint
./robopaint: error while loading shared libraries: libnss3.so: cannot open
shared object file: No such file or directory

**Comment by tsmaster** [comment]
... which is already installed, or at least the latest version of it is.

**Comment by techninja** [comment]
Poo! Well, we're not out of the common territory yet, this pulled up numerous results, and this link which seems promising. Glad chrome is so popular :)

http://superuser.com/questions/709524/google-chrome-dependency-error-libnss3

**Comment by techninja** [comment]
I have not had this issue with Electron (at least not yet). I'm guessing they've done a better job of bundling Chromium. Closing this as the next release will be on Electron.

**Comment by tim-taylor** [comment]
I just bought a watercolorbot and I'm struggling to get robopaint working on my Linux machine (running the latest Kubuntu 15.10), getting the same issues with libudev, then libgtk-x11 etc. Is the new Electron release coming out soon? Should I keep struggling to get the current version working, or wait for the new release?

**Comment by tim-taylor** [comment]
Okay, I've just got this running. I've posted details of my solution on the discussion group at https://groups.google.com/forum/#!forum/wcb-discuss

**Comment by techninja** [comment]
@tim-taylor  Sorry again for your issues. Follow the beta release ticket here: #237, we'll be getting it out quite soon. I dev nearly exclusively on Linux, and I have to say my experiences running on Electron have been lightyears ahead of node-webkit's current problems. Unfortunately we won't have a nice installer/.deb file yet for Linux, but it's in the works.

**Comment by tim-taylor** [comment]
Sounds good! Looking forward to the new release, but in the meantime I've now started producing my first paintings :-)
