### ISSUE TITLE
Buffer performance improvements

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#200]
Certain buffer smoothing values lead to unpredictable performance. For example, redrawing a certain part of a line, or repeatedly lifting and lowering the pen, even when drawing a single continuous shape.

**Comment by techninja** [comment]
Buffer smoothing setting in RP is basically a direct setter to CNCServer, so this is totally its problem. Good news: I believe I found this issue a few days ago and have fixed it here: https://github.com/techninja/cncserver/commit/d1b407e2033150aabb547743ffe16c7a59a7102b

Basically: When you run a bunch of functions, with one right after the other, called in one big line, nothing else is allowed to run. If this long running line just keeps going (either with _thousands_ of low millisecond operations, or a number of 50+ millisecond operations that have been cut down to nothing from a high-ish smoothing setting), things get stuck, because the only way to break out of this is by leaving the function without running the next function, but trigger the next call **_indirectly_** with a timeout.

This would have happened normally, but buffer smoothing and direct calls smooth operations a LOT, so what I've done is added an arbitrary limit to the maximum number of functionally consecutive buffer executions. This breaks us out of the lock at least once every 1/6th of a second, enough for ensuring items have been sent, and other buffering operations to be run.

Two more performance bonuses in the Paper.JS branch:
 1. All motion paths are drawn in front of the user, and are then ordered in first->last with path reversal. This means all the end paths have to exist first, so the user waits while nothing happens on the bot, though it's fun to look at on screen. No more print slowdowns because of spool processing.
 2. On by default, printTillEmpty ensures that everything moves from the local send queue into the actual cncserver buffer before anything is executed. A status message and full progress bar is provided, though it does mean the user has to wait a little longer before things print, it means that when it starts, it should be fully uninterrupted.
